### ISSUE TITLE
code demo run error

### ISSUE THREAD

**Issue by 2577935553** [styalai/xLSTM-pytorch#1]
![image](https://github.com/styalai/xLSTM-pytorch/assets/71956767/ffde9df8-70fe-461a-8753-9e1796aec7a1)
![image](https://github.com/styalai/xLSTM-pytorch/assets/71956767/f0fecc1d-07e8-412b-925d-36faaa58cba0)
![image](https://github.com/styalai/xLSTM-pytorch/assets/71956767/297afbe8-9105-4e24-b792-31b61130e26e)

**Comment by styalai** [comment]
Ok I will solve the problem it work with batch_size=1

**Comment by styalai** [comment]
👌
